### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jxn78** [KitsuneLab-Development/K4-Arenas#28]
09:50:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Unknown' was not present in the dictionary.
   at K4Arenas.Models.ArenaPlayer.ShowCenterWeaponSubPreferenceMenu(WeaponType weaponType)
   at Menu.KitsuneMenu.<>c__DisplayClass36_0.<ShowScrollableMenu>g__wrappedCallback|4(MenuButtons buttons, MenuBase m, MenuItem selected)
   at Menu.KitsuneMenu.HandleMenuButton(MenuButtons buttons, MenuBase menu, MenuItem selectedItem, CCSPlayerController controller)
   at Menu.KitsuneMenu.HandleButtonPress(CCSPlayerController controller, MenuButtons currentButtons, MenuBase menu, MenuItem selectedItem, DateTime currentTime)
   at Menu.KitsuneMenu.OnTickListener()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
09:50:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Unknown' was not present in the dictionary.
   at K4Arenas.Models.ArenaPlayer.ShowCenterWeaponSubPreferenceMenu(WeaponType weaponType)
   at Menu.KitsuneMenu.<>c__DisplayClass36_0.<ShowScrollableMenu>g__wrappedCallback|4(MenuButtons buttons, MenuBase m, MenuItem selected)
   at Menu.KitsuneMenu.HandleMenuButton(MenuButtons buttons, MenuBase menu, MenuItem selectedItem, CCSPlayerController controller)
   at Menu.KitsuneMenu.HandleButtonPress(CCSPlayerController controller, MenuButtons currentButtons, MenuBase menu, MenuItem selectedItem, DateTime currentTime)
   at Menu.KitsuneMenu.OnTickListener()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
09:50:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Unknown' was not present in the dictionary.
   at K4Arenas.Models.ArenaPlayer.ShowCenterWeaponSubPreferenceMenu(WeaponType weaponType)
   at Menu.KitsuneMenu.<>c__DisplayClass36_0.<ShowScrollableMenu>g__wrappedCallback|4(MenuButtons buttons, MenuBase m, MenuItem selected)
   at Menu.KitsuneMenu.HandleMenuButton(MenuButtons buttons, MenuBase menu, MenuItem selectedItem, CCSPlayerController controller)
   at Menu.KitsuneMenu.HandleButtonPress(CCSPlayerController controller, MenuButtons currentButtons, MenuBase menu, MenuItem selectedItem, DateTime currentTime)
   at Menu.KitsuneMenu.OnTickListener()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
09:50:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Unknown' was not present in the dictionary.
   at K4Arenas.Models.ArenaPlayer.ShowCenterWeaponSubPreferenceMenu(WeaponType weaponType)
   at Menu.KitsuneMenu.<>c__DisplayClass36_0.<ShowScrollableMenu>g__wrappedCallback|4(MenuButtons buttons, MenuBase m, MenuItem selected)
   at Menu.KitsuneMenu.HandleMenuButton(MenuButtons buttons, MenuBase menu, MenuItem selectedItem, CCSPlayerController controller)
   at Menu.KitsuneMenu.HandleButtonPress(CCSPlayerController controller, MenuButtons currentButtons, MenuBase menu, MenuItem selectedItem, DateTime currentTime)
   at Menu.KitsuneMenu.OnTickListener()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
09:50:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Unknown' was not present in the dictionary.
   at K4Arenas.Models.ArenaPlayer.ShowCenterWeaponSubPreferenceMenu(WeaponType weaponType)
   at Menu.KitsuneMenu.<>c__DisplayClass36_0.<ShowScrollableMenu>g__wrappedCallback|4(MenuButtons buttons, MenuBase m, MenuItem selected)
   at Menu.KitsuneMenu.HandleMenuButton(MenuButtons buttons, MenuBase menu, MenuItem selectedItem, CCSPlayerController controller)
   at Menu.KitsuneMenu.HandleButtonPress(CCSPlayerController controller, MenuButtons currentButtons, MenuBase menu, MenuItem selectedItem, DateTime currentTime)
   at Menu.KitsuneMenu.OnTickListener()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
09:50:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Unknown' was not present in the dictionary.
   at K4Arenas.Models.ArenaPlayer.ShowCenterWeaponSubPreferenceMenu(WeaponType weaponType)
   at Menu.KitsuneMenu.<>c__DisplayClass36_0.<ShowScrollableMenu>g__wrappedCallback|4(MenuButtons buttons, MenuBase m, MenuItem selected)
   at Menu.KitsuneMenu.HandleMenuButton(MenuButtons buttons, MenuBase menu, MenuItem selectedItem, CCSPlayerController controller)
   at Menu.KitsuneMenu.HandleButtonPress(CCSPlayerController controller, MenuButtons currentButtons, MenuBase menu, MenuItem selectedItem, DateTime currentTime)
   at Menu.KitsuneMenu.OnTickListener()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
09:50:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Unknown' was not present in the dictionary.
   at K4Arenas.Models.ArenaPlayer.ShowCenterWeaponSubPreferenceMenu(WeaponType weaponType)
   at Menu.KitsuneMenu.<>c__DisplayClass36_0.<ShowScrollableMenu>g__wrappedCallback|4(MenuButtons buttons, MenuBase m, MenuItem selected)
   at Menu.KitsuneMenu.HandleMenuButton(MenuButtons buttons, MenuBase menu, MenuItem selectedItem, CCSPlayerController controller)
   at Menu.KitsuneMenu.HandleButtonPress(CCSPlayerController controller, MenuButtons currentButtons, MenuBase menu, MenuItem selectedItem, DateTime currentTime)
   at Menu.KitsuneMenu.OnTickListener()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
09:50:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Unknown' was not present in the dictionary.
   at K4Arenas.Models.ArenaPlayer.ShowCenterWeaponSubPreferenceMenu(WeaponType weaponType)
   at Menu.KitsuneMenu.<>c__DisplayClass36_0.<ShowScrollableMenu>g__wrappedCallback|4(MenuButtons buttons, MenuBase m, MenuItem selected)
   at Menu.KitsuneMenu.HandleMenuButton(MenuButtons buttons, MenuBase menu, MenuItem selectedItem, CCSPlayerController controller)
   at Menu.KitsuneMenu.HandleButtonPress(CCSPlayerController controller, MenuButtons currentButtons, MenuBase menu, MenuItem selectedItem, DateTime currentTime)
   at Menu.KitsuneMenu.OnTickListener()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
09:50:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Unknown' was not present in the dictionary.
   at K4Arenas.Models.ArenaPlayer.ShowCenterWeaponSubPreferenceMenu(WeaponType weaponType)
   at Menu.KitsuneMenu.<>c__DisplayClass36_0.<ShowScrollableMenu>g__wrappedCallback|4(MenuButtons buttons, MenuBase m, MenuItem selected)
   at Menu.KitsuneMenu.HandleMenuButton(MenuButtons buttons, MenuBase menu, MenuItem selectedItem, CCSPlayerController controller)
   at Menu.KitsuneMenu.HandleButtonPress(CCSPlayerController controller, MenuButtons currentButtons, MenuBase menu, MenuItem selectedItem, DateTime currentTime)
   at Menu.KitsuneMenu.OnTickListener()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by jxn78** [comment]
@K4ryuu

**Comment by K4ryuu** [comment]
Going to check on it in the upcoming days

**Comment by K4ryuu** [comment]
It is pushed to 1.5.1 release that was made by @originalaidn.
Update your plugin and the issue wont happen anymore.
Thank you for the patience!
