### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jxn78** [KitsuneLab-Development/K4-Arenas#31]
![IMG_20241112_205600](https://github.com/user-attachments/assets/0f25211d-beb8-4169-819f-838e6497c66e)

**Comment by jxn78** [comment]
@K4ryuu @originalaidn help me

**Comment by K4ryuu** [comment]
I pushed a new release with updated CounterStrikeSharp API. Possibly that fixes your issue, but please give me a feedback about that.

**Comment by jxn78** [comment]
@K4ryuu 
`08:47:21 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid game event
   at CounterStrikeSharp.API.Core.NativeAPI.GetEventPlayerController(IntPtr gameevent, String name) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 965
   at CounterStrikeSharp.API.Modules.Events.GameEvent.GetPlayer(String name) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Events/GameEvent.cs:line 111
   at K4Arenas.Plugin.<>c.<Initialize_Events>b__55_10(EventRoundMvp event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100`

**Comment by jxn78** [comment]
pls help me

**Comment by K4ryuu** [comment]
Did you updated the plugin to https://github.com/KitsuneLab-Development/K4-Arenas/releases/tag/v1.5.2?

**Comment by jxn78** [comment]
yes

**Comment by K4ryuu** [comment]
I cannot reproduce the issue with the latest build, so I close the issue.
I recommend you to update your CSS, keep the files, gamedata up-to-date.

In worts case scenario download runtime version and update full CSS.
